name: sere

services:
  sere:
    container_name: sere
    image: ghcr.io/bostannnn/sere:latest
    restart: unless-stopped
    ports:
      - 6001:6001
    environment:
      - RISU_DATA_ROOT=/app/data/users/default
    volumes:
      - sere-data:/app/data

volumes:
  sere-data:
