import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { mount, tick, unmount } from "svelte";
import { get } from "svelte/store";
import AlertComp from "src/lib/Others/AlertComp.svelte";
import { alertGenerationInfoStore } from "src/ts/alert";
import { alertStore } from "src/ts/stores.svelte";

const hoisted = vi.hoisted(() => ({
  getFetchLogs: vi.fn(() => [
    {
      url: "https://example.test/data/llm/execute",
      success: false,
      status: 500,
      date: "2026-02-27T13:00:00.000Z",
      body: {
        mode: "chat",
        provider: "openrouter",
        model: "openrouter/test-model",
        chatId: "chat-abcdef1234",
      },
      header: {
        "content-type": "application/json",
      },
      response: {
        ok: false,
      },
    },
  ]),
  getFetchData: vi.fn(() => null),
  getServerLLMLogs: vi.fn(async () => []),
  getChatBranches: vi.fn(() => []),
  isNodeServer: false,
  getCurrentCharacter: vi.fn(() => ({
    chats: [
      {
        message: [
          {
            data: "Branch preview",
          },
        ],
      },
    ],
  })),
  clipboardWriteText: vi.fn(async () => undefined),
}));

vi.mock(import("src/ts/alert"), async () => {
  const { writable } = await import("svelte/store");
  return {
    alertGenerationInfoStore: writable({
      idx: 1,
      genInfo: {
        generationId: "gen-1",
        inputTokens: 50,
        outputTokens: 10,
        maxContext: 100,
        model: "openrouter/test-model",
      },
    }),
  };
});

vi.mock(import("src/ts/stores.svelte"), async () => {
  const { writable } = await import("svelte/store");
  return {
    DBState: {
      db: {
        sourcemapTranslate: false,
        botPresetsId: 0,
        botPresets: [
          {
            image: "",
            regex: [],
          },
        ],
        characters: [
          {
            type: "char",
            chaId: "char-1",
            image: "",
            chatPage: 0,
            chats: [
              {
                id: "chat-1",
                message: [
                  {
                    role: "user",
                    data: "Hello",
                    time: 1710000000000,
                    chatId: "msg-0",
                    saying: "User",
                    promptInfo: {},
                  },
                  {
                    role: "char",
                    data: "Reply",
                    time: 1710000001000,
                    chatId: "msg-1",
                    saying: "Bot",
                    promptInfo: {
                      promptName: "Preset A",
                      promptToggles: [{ key: "safe", value: "on" }],
                      promptText: [{ role: "system", content: "You are helpful" }],
                    },
                  },
                ],
                memoryData: {
                  summaries: [{ text: "Summary 1", chatMemos: [], isImportant: false }],
                  categories: [{ id: "", name: "Unclassified" }],
                  lastSelectedSummaries: [],
                },
              },
            ],
          },
        ],
      },
    },
    selectedCharID: writable(0),
    alertStore: writable({
      type: "none",
      msg: "",
    }),
  };
});

vi.mock(import("src/lang"), () => {
  const language = new Proxy(
    {
      sessionLogs: "Session Logs",
      serverLLMLogs: "Server LLM Logs",
      collapseAll: "Collapse all",
      expandAll: "Expand all",
      noSessionLogs: "No session logs yet.",
      noServerLLMLogs: "No server LLM logs yet.",
      hideErrorDetails: "Hide details",
      showErrorDetails: "Show details",
      translating: "Translating",
      showOriginal: "Show original",
      translateCode: "Translate code",
      generatedByAIDisclaimer: "Generated by AI",
      tokens: "Tokens",
      metaData: "Metadata",
      log: "Log",
      prompt: "Prompt",
      copied: "Copied",
      copy: "Copy",
      promptInfoEmptyMessage: "No prompt info",
      promptInfoEmptyToggle: "No toggles",
      promptInfoEmptyText: "No prompt text",
      inputTokens: "Input tokens",
      outputTokens: "Output tokens",
      maxContextSize: "Max context",
      tokenWarning: "Token warning",
      errors: {
        requestLogRemoved: "Request log removed",
        requestLogRemovedDesc: "Request log no longer exists",
      },
      shareExport: "Share Export",
      type: "Type",
      risuMDesc: "Module export",
      risupresetDesc: "Preset export",
      ccv3Desc: "CCV3 export",
      jsonDesc: "JSON export",
      ccv2Desc: "CCV2 export",
      v2Warning: "V2 warning",
      format: "Format",
      export: "Export",
      notCharxWarn: "CHARX warning",
      preview: "Preview",
      addCharacter: "Add character",
      chatOptions: "Chat options",
      importCharacter: "Import character",
      createfromScratch: "Create from scratch",
      createGroup: "Create group",
      cancel: "Cancel",
      createCopy: "Create copy",
      bindPersona: "Bind persona",
    } as Record<string, unknown>,
    {
      get(target, property) {
        if (typeof property === "string" && property in target) {
          return target[property];
        }
        return String(property);
      },
    },
  );
  return { language };
});

vi.mock(import("src/ts/globalApi.svelte"), () => ({
  aiLawApplies: vi.fn(() => true),
  openURL: vi.fn(),
  getFetchLogs: hoisted.getFetchLogs,
  getFetchData: hoisted.getFetchData,
  getServerLLMLogs: hoisted.getServerLLMLogs,
}));
vi.mock(import("src/ts/platform"), () => ({
  get isNodeServer() {
    return hoisted.isNodeServer;
  },
}));
vi.mock(import("src/ts/characters"), () => ({
  getCharImage: vi.fn(async () => null),
}));
vi.mock(import("src/ts/parser.svelte"), () => ({
  ParseMarkdown: vi.fn(async () => ""),
}));
vi.mock(import("src/ts/characterCards"), () => ({
  isCharacterHasAssets: vi.fn(() => false),
}));
vi.mock(import("src/ts/tokenizer"), () => ({
  tokenize: vi.fn(async () => 13),
}));
vi.mock(import("src/ts/gui/colorscheme"), async () => {
  const { writable } = await import("svelte/store");
  return {
    ColorSchemeTypeStore: writable(false),
  };
});
vi.mock(import("src/ts/gui/branches"), () => ({
  getChatBranches: hoisted.getChatBranches,
}));
vi.mock(import("src/ts/storage/database.svelte"), () => ({
  getCurrentCharacter: hoisted.getCurrentCharacter,
}));
vi.mock(import("src/ts/sourcemap"), () => ({
  translateStackTrace: vi.fn(async () => "Translated stack trace"),
}));
vi.mock(import("src/lib/SideBars/BarIcon.svelte"), async () => ({
  default: (await import("./test-stubs/SimplePanelStub.svelte")).default,
}));
vi.mock(import("src/lib/UI/GUI/TextInput.svelte"), async () => ({
  default: (await import("./test-stubs/BindableFieldStub.svelte")).default,
}));
vi.mock(import("src/lib/UI/GUI/SelectInput.svelte"), async () => ({
  default: (await import("./test-stubs/BindableFieldStub.svelte")).default,
}));
vi.mock(import("src/lib/UI/GUI/OptionInput.svelte"), async () => ({
  default: (await import("./test-stubs/SimplePanelStub.svelte")).default,
}));
vi.mock(import("src/lib/UI/GUI/TextAreaInput.svelte"), async () => ({
  default: (await import("./test-stubs/BindableFieldStub.svelte")).default,
}));
vi.mock(import("src/lib/Setting/Pages/Module/ModuleChatMenu.svelte"), async () => ({
  default: (await import("./test-stubs/SimplePanelStub.svelte")).default,
}));

async function flushUi() {
  await tick();
  await Promise.resolve();
  await new Promise((resolve) => setTimeout(resolve, 0));
}

describe("alert comp extra runtime smoke", () => {
  let app: ReturnType<typeof mount> | null = null;

  beforeEach(() => {
    document.body.innerHTML = "";
    hoisted.getFetchLogs.mockClear();
    hoisted.getFetchData.mockReset();
    hoisted.getFetchData.mockReturnValue(null);
    hoisted.getServerLLMLogs.mockReset();
    hoisted.getServerLLMLogs.mockResolvedValue([]);
    hoisted.getChatBranches.mockReset();
    hoisted.getChatBranches.mockReturnValue([]);
    hoisted.getCurrentCharacter.mockReset();
    hoisted.getCurrentCharacter.mockReturnValue({
      chats: [{ message: [{ data: "Branch preview" }] }],
    });
    hoisted.clipboardWriteText.mockClear();
    hoisted.isNodeServer = false;
    Object.defineProperty(navigator, "clipboard", {
      configurable: true,
      value: {
        writeText: hoisted.clipboardWriteText,
      },
    });
    alertGenerationInfoStore.set({
      idx: 1,
      genInfo: {
        generationId: "gen-1",
        inputTokens: 50,
        outputTokens: 10,
        maxContext: 100,
        model: "openrouter/test-model",
      },
    });
    alertStore.set({
      type: "none",
      msg: "",
    });
  });

  afterEach(async () => {
    if (app) {
      await unmount(app);
      app = null;
    }
    document.body.innerHTML = "";
  });

  it("writes card export selections back to alertStore", async () => {
    alertStore.set({
      type: "cardexport",
      msg: "",
      submsg: "",
    });

    const target = document.createElement("div");
    document.body.appendChild(target);
    app = mount(AlertComp, { target });
    await flushUi();

    const exportButton = document.querySelector(".alert-cardexport-submit") as HTMLButtonElement | null;
    expect(exportButton).not.toBeNull();
    exportButton?.click();
    await flushUi();

    expect(get(alertStore).type).toBe("none");
    expect(JSON.parse(get(alertStore).msg)).toEqual({
      format: "json",
      includeChats: false,
      includeMemories: false,
      includeEvolution: false,
      cancelled: false,
    });
  });

  it("renders requestdata log tab and copies the request body", async () => {
    hoisted.getFetchData.mockReturnValue({
      url: "https://example.test/data/llm/generate",
      body: {
        hello: "world",
      },
      response: {
        ok: true,
      },
    });
    alertStore.set({
      type: "requestdata",
      msg: "gen-1",
    });

    const target = document.createElement("div");
    document.body.appendChild(target);
    app = mount(AlertComp, { target });
    await flushUi();

    const toolbarButtons = [...document.querySelectorAll(".alert-inline-toolbar .ds-ui-button")] as HTMLButtonElement[];
    expect(toolbarButtons.length).toBeGreaterThanOrEqual(4);
    toolbarButtons[2]?.click();
    await flushUi();

    const copyButtons = [...document.querySelectorAll(".alert-requestdata-actions .ds-ui-button")] as HTMLButtonElement[];
    expect(copyButtons.length).toBeGreaterThanOrEqual(3);
    copyButtons[2]?.click();
    await flushUi();

    expect(hoisted.clipboardWriteText).toHaveBeenCalledWith(expect.stringContaining('"hello": "world"'));
    const codeBlocks = [...document.querySelectorAll(".alert-code-block")] as HTMLElement[];
    expect(
      codeBlocks.some((block) =>
        (block.textContent ?? "").includes("https://example.test/data/llm/generate"),
      ),
    ).toBe(true);
  });

  it("falls back to the best durable server log when client request data is missing", async () => {
    hoisted.isNodeServer = true;
    hoisted.getFetchData.mockReturnValue(null);
    hoisted.getServerLLMLogs.mockResolvedValue([
      {
        requestId: "req-wrong",
        timestamp: "2024-03-09T15:59:59.000Z",
        endpoint: "generate",
        mode: "model",
        path: "/data/llm/generate",
        request: JSON.stringify({
          requestBody: {
            model: "other-model",
            messages: [{ role: "user", content: "Different prompt" }],
          },
        }),
        response: JSON.stringify({ id: "resp-wrong" }),
      },
      {
        requestId: "req-good",
        timestamp: "2024-03-09T16:00:01.050Z",
        endpoint: "generate",
        mode: "model",
        path: "/data/llm/generate",
        status: 200,
        ok: true,
        durationMs: 1200,
        request: JSON.stringify({
          requestBody: {
            model: "openrouter/test-model",
            messages: [
              { role: "system", content: "You are helpful" },
              { role: "user", content: "Hello" },
            ],
          },
        }),
        response: JSON.stringify({
          id: "resp-good",
          ok: true,
        }),
        error: null,
      },
    ]);
    alertStore.set({
      type: "requestdata",
      msg: "missing-gen-id",
    });

    const target = document.createElement("div");
    document.body.appendChild(target);
    app = mount(AlertComp, { target });
    await flushUi();

    const toolbarButtons = [...document.querySelectorAll(".alert-inline-toolbar .ds-ui-button")] as HTMLButtonElement[];
    expect(toolbarButtons.length).toBeGreaterThanOrEqual(4);
    toolbarButtons[2]?.click();
    await flushUi();
    await flushUi();

    expect(hoisted.getServerLLMLogs).toHaveBeenCalledWith({ limit: 200, chatId: "chat-1" });

    const codeBlocks = [...document.querySelectorAll(".alert-code-block")] as HTMLElement[];
    expect(codeBlocks.some((block) => (block.textContent ?? "").includes("/data/llm/generate [req:req-good]"))).toBe(true);
    expect(codeBlocks.some((block) => (block.textContent ?? "").includes('"model": "openrouter/test-model"'))).toBe(true);

    const copyButton = document.querySelector(".alert-requestdata-actions .ds-ui-button") as HTMLButtonElement | null;
    expect(copyButton).not.toBeNull();
    copyButton?.click();
    await flushUi();

    expect(hoisted.clipboardWriteText).toHaveBeenCalledWith(
      expect.stringContaining('"model": "openrouter/test-model"'),
    );
  });

  it("shows branch hover preview and closes the overlay", async () => {
    hoisted.getChatBranches.mockReturnValue([
      {
        x: 1,
        y: 1,
        connectX: 1,
        multiChild: false,
        chatId: 0,
      },
    ]);
    hoisted.getCurrentCharacter.mockReturnValue({
      chats: [
        {
          message: [
            {
              data: "Branch preview",
            },
          ],
        },
      ],
    });
    alertStore.set({
      type: "branches",
      msg: "",
    });

    const target = document.createElement("div");
    document.body.appendChild(target);
    app = mount(AlertComp, { target });
    await flushUi();

    const branchNode = document.querySelector(".alert-branch-node") as HTMLElement | null;
    expect(branchNode).not.toBeNull();
    branchNode?.dispatchEvent(new MouseEvent("mouseenter", { bubbles: true }));
    await flushUi();

    const tooltip = document.querySelector(".alert-branch-tooltip") as HTMLElement | null;
    expect((tooltip?.textContent ?? "").includes("Branch preview")).toBe(true);

    const closeButton = document.querySelector(".alert-branch-close-button") as HTMLButtonElement | null;
    expect(closeButton).not.toBeNull();
    closeButton?.click();
    await flushUi();
    expect(get(alertStore).type).toBe("none");
  });
});
